<%
  def user_for(host) = Net::SSH::Config.for(host).fetch(:user, ENV.fetch('USER', nil))
  def project_root = KAMAL.instance_variable_get(:@config_kwargs)[:config_file].join('../..')
  def ruby_version = project_root.join('.ruby-version').read.strip
  def redirect_hosts
    YAML.load_file(project_root.join('redirects.yml'))['redirects'].map { it['from'] }.reject { it == 'default' }
  end
%>

service: redirect-woozle
image: werebus/redirect-woozle

servers:
  web:
    - apps.wereb.us

ssh:
  user: <%= user_for 'apps.wereb.us' %>

proxy:
  ssl: true
  hosts: [ <%= redirect_hosts.join(', ') %> ]

registry:
  server: ghcr.io
  username: werebus
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  args:
    RUBY_VERSION: <%= ruby_version %>
